basePath: /
definitions:
  model.Movie:
    properties:
      released:
        type: integer
      tagline:
        type: string
      title:
        description: gorm.Model
        type: string
    type: object
  model.Person:
    properties:
      acted:
        type: boolean
      born:
        type: integer
      direct:
        type: boolean
      name:
        type: string
      releaseMovie:
        type: integer
      titleMovie:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: fiber aplication with neo4j
  version: "1.0"
paths:
  /movie:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Show all movies
      tags:
      - movie
  /movie/:
    post:
      parameters:
      - description: Movie model
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/model.Movie'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Create a movies
      tags:
      - movie
  /movie/{title}/{released}:
    delete:
      parameters:
      - description: Movie name
        in: path
        name: title
        required: true
        type: string
      - description: Movie released year
        in: path
        name: released
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      summary: Delete a movie
      tags:
      - movie
    get:
      parameters:
      - description: Movie name
        in: path
        name: title
        required: true
        type: string
      - description: Movie released year
        in: path
        name: released
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Get movie by id
      tags:
      - movie
    put:
      parameters:
      - description: Movie name
        in: path
        name: title
        required: true
        type: string
      - description: Movie released year
        in: path
        name: released
        required: true
        type: integer
      - description: Movie model
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/model.Movie'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Edit a movies
      tags:
      - movie
  /person:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Show all persons
      tags:
      - person
  /person/:
    post:
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      - description: Person model
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/model.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Create a person
      tags:
      - person
  /person/{id}:
    delete:
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      summary: Delete a person
      tags:
      - person
    put:
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      - description: Person model
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/model.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Edit a person
      tags:
      - person
  /person/{name}/{born}:
    get:
      parameters:
      - description: name Person
        in: path
        name: name
        required: true
        type: string
      - description: year person born
        in: path
        name: born
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Get person by id
      tags:
      - person
swagger: "2.0"
